
# CMakeLists.txt generated by STM32CubeAI Studio


# AI sources
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Misc/Src/syscalls.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Misc/Src/lc_print.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Misc/Src/ai_device_adaptor.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Misc/Src/aiTestUtility.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Misc/Src/aiTestHelper_ST_AI.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/stm32msg.pb.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/pb_encode.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/pb_decode.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/pb_common.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/aiValidation_ST_AI.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/aiPbMgr.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/aiPbMemRWServices.c
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Src/aiPbIO.c
)


# Include directories
target_include_directories(${CMAKE_PROJECT_NAME} PUBLIC
    ${CMAKE_SOURCE_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Inc
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Misc/Inc
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Validation/Inc
)



# Library directories
target_link_directories(${CMAKE_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Lib
)

# Precompiled AI runtime libraries
target_link_libraries(${CMAKE_PROJECT_NAME}
    ${CMAKE_CURRENT_LIST_DIR}/../Middlewares/ST/AI/Lib/NetworkRuntime1201_CM33_GCC.a
    m
)

