
# CMakeLists.txt generated by STM32CubeAI Studio


# AI sources
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/App/network_data.c
    ${CMAKE_CURRENT_LIST_DIR}/App/network.c
    ${CMAKE_CURRENT_LIST_DIR}/App/user_init.c
    ${CMAKE_CURRENT_LIST_DIR}/App/app_x-cube-ai.c
    ${CMAKE_CURRENT_LIST_DIR}/App/network_weights.c
)

# Add compile definitions, equivalent to "-D"
target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE
    HAVE_NETWORK_INFO
)

# Include directories
target_include_directories(${CMAKE_PROJECT_NAME} PUBLIC
    ${CMAKE_SOURCE_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/App
)





